name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v2

      - name: TFLint Check
        run: tflint

      - name: Terraform Init
        working-directory: GKE_DevSecops
        run: terraform init

      - name: Terraform Format
        working-directory: GKE_DevSecops
        run: terraform fmt

      - name: Terraform Validate
        working-directory: GKE_DevSecops
        run: terraform validate

      - name: Terraform Plan
        working-directory: GKE_DevSecops
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: GKE_DevSecops
        run: terraform apply -auto-approve tfplan

